version: "3.1"

services:
    mysql:
      ports:
        - "${MYSQL_PORT}:3306"

    beanstalkd:
      ports:
        - "${BEANSTALKD_HOST_PORT}:11300"

    beanstalkd-console:
      image: schickling/beanstalkd-console
      container_name: beanstalkd-console
      ports:
        - "${BEANSTALKD_CONSOLE_HOST_PORT}:2080"

    rabbitmq:
      ports:
        - "${RABBITMQ_NODE_HOST_PORT}:5672"
        - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
        - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"

    redis:
      ports:
        - "${REDIS_PORT_HOST}:6379"

    webserver:
      ports:
        - "${APP_PORT}:80"
        - "${APP_PORT_SSL}:443"

    elasticsearch:
      ports:
        - "9200:9200"
