version: "3.1"

services:
    mysql:
      ports:
        - "${MYSQL_PORT}:3306"

    beanstalkd:
      ports:
        - "${BEANSTALKD_HOST_PORT}:11300"

    beanstalkd-console:
      image: schickling/beanstalkd-console
      container_name: beanstalkd-console
      ports:
        - "${BEANSTALKD_CONSOLE_HOST_PORT}:2080"

    redis:
      ports:
        - "${REDIS_PORT_HOST}:6379"

    webserver:
      ports:
        - "${APP_PORT}:80"

    elasticsearch:
      ports:
        - "9200:9200"
